name: Auto Renew

on:
  schedule:
    - cron: '0 */5 * * *'
  workflow_dispatch:

jobs:
  renew:
    runs-on: ubuntu-latest

    steps:
      - name: Renew Server
        run: |
          curl -s -X POST \
          -H "Authorization: Bearer ${{ secrets.API_KEY }}" \
          -H "Accept: application/json" \
          -H "Content-Type: application/json" \
          "https://panel.epichost.pl/api/client/freeservers/11b358af-47f4-414b-81d8-8879dae2b7be/renew"
